###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=teste
        - MYSQL_DATABASE=teste
        - MYSQL_USER=user_teste
        - MYSQL_PASSWORD=user_teste
      ports:
        - "3306:3306"

    redis:
      image: redis:alpine
      ports:
        - "6379:6379"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - ./src:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: docker/php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini